name: EBAC -EXERCICO 26

on:
  push:
    branches: [m26]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Verify Cypress cache
        run: npx cypress cache path && npx cypress cache list
      - name: Install Cypress
        run: npx cypress install
      - name: Fix Cypress permissions
        run: chmod +x node_modules/.bin/cypress
      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          install-command: npm install
          browser: chrome
          start: npm start
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: cypress/reports/mochawesome
